roi_vertices:
  - [1200, 350]    # верхний левый угол
  - [0, 1000]      # нижний левый угол
  - [1700, 1500]   # нижний правый угол
  - [1800, 300]    # верхний правый угол

#model params
classes : [2, 3, 5, 7]
confidence_threshold : 0.7
nms_threshold : 0.01